---
- name: Enable apache2 proxy modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_ajp
    - proxy_http
    - rewrite
    - deflate
    - headers
    - proxy_balancer
    - proxy_connect
    - proxy_html
    - ssl
    - proxy_wstunnel
  when: sonarr_HTTP_server == "apache2"
  notify: Restart {{ sonarr_HTTP_server }}

- name: Remove default {{ sonarr_HTTP_server }} site
  file:
    path: /etc/{{ sonarr_HTTP_server }}/sites-enabled/{{ item }}
    state: absent
  loop:
    - default
    - 000-default.conf
    - default-ssl.conf
  when: sonarr_remove_default
  notify: Restart {{ sonarr_HTTP_server }}

- name: Check if letsencrypt certificate exists
  stat:
    path: /etc/letsencrypt/live/{{ sonarr_FQDN | first }}/fullchain.pem
  register: letsencrypt_certificate

- name: Copy {{ sonarr_HTTP_server }} configuration
  template:
    src: sonarr.conf-{{ sonarr_HTTP_server }}.j2
    dest: /etc/{{ sonarr_HTTP_server }}/sites-available/sonarr.conf
  notify: Restart {{ sonarr_HTTP_server }}

- name: Enable sonarr site
  file:
    src: /etc/{{ sonarr_HTTP_server }}/sites-available/sonarr.conf
    dest: /etc/{{ sonarr_HTTP_server }}/sites-enabled/sonarr.conf
    state: link
  notify: Restart {{ sonarr_HTTP_server }}
...
