---
- name: Create {{ sonarr_group }} group
  group:
    name: "{{ sonarr_group }}"
    state: present

- name: Create {{ sonarr_user }} user
  user:
    name: "{{ sonarr_user }}"
    group: "{{ sonarr_group }}"
    state: present
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Import Sonarr Team GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
    state: present
  register: apt_key_result
  retries: 3
  until: apt_key_result is succeeded

- name: Add Sonarr repository
  apt_repository:
    repo: >
      deb https://apt.sonarr.tv/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    state: present

- name: Install Sonarr
  apt:
    update_cache: true
    name: sonarr
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: configure Sonarr service
  ini_file:
    path: /lib/systemd/system/sonarr.service
    section: Service
    option: "{{ item.option }}"
    state: present
    value: "{{ item.value }}"
  loop:
    - option: User
      value: "{{ sonarr_user }}"
    - option: Group
      value: "{{ sonarr_group }}"
  notify: Restart Sonarr

- name: Set correct ownership of Sonarr directory
  file:
    path: /var/lib/sonarr
    state: directory
    recurse: true
    owner: "{{ sonarr_user }}"
    group: "{{ sonarr_group }}"
  notify: Restart Sonarr

- name: Enable Sonarr
  systemd:
    name: sonarr
    state: started
    enabled: true
...
