---
- name: Install sonarr
  include_tasks: install.yml

- name: Generate self signed SSL certificate
  include_role:
    name: hadrienpatte.self_signed_certificate
  vars:
    self_signed_certificate_FQDN: "{{ sonarr_FQDN }}"
    self_signed_certificate_key_path: "{{ sonarr_certificate_path }}"
    self_signed_certificate_path: "{{ sonarr_certificate_path }}"
  when: sonarr_generate_self_signed_certificate

- name: Configure {{ sonarr_HTTP_server }}
  include_tasks: HTTP_server.yml

- name: Install and configure certbot
  include_tasks: certbot.yml
  when: sonarr_letsencrypt

- name: Reconfigure {{ sonarr_HTTP_server }}
  include_tasks: HTTP_server.yml
  when: sonarr_letsencrypt
...
