---
- name: Restart Sonarr
  systemd:
    name: sonarr
    state: restarted
    daemon_reload: true

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
...
