---
platforms:
  - name: debian-buster
    image: jrei/systemd-debian:10
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "80"
      - "443"
      - "8989"
verifier:
  name: testinfra
...
