---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: jessie
    image: debian:jessie
  - name: stretch
    image: debian:stretch
  - name: buster
    image: debian:buster
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
...
